/* eslint-disable */
// source: mathgame/protobuf/app.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var mathgame_protobuf_client_pb = require('../../mathgame/protobuf/client_pb.js');
goog.object.extend(proto, mathgame_protobuf_client_pb);
goog.exportSymbol('proto.mathgame.protobuf.Message', null, global);
goog.exportSymbol('proto.mathgame.protobuf.Message.PayloadCase', null, global);
goog.exportSymbol('proto.mathgame.protobuf.Message.Type', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mathgame.protobuf.Message = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.mathgame.protobuf.Message.oneofGroups_);
};
goog.inherits(proto.mathgame.protobuf.Message, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mathgame.protobuf.Message.displayName = 'proto.mathgame.protobuf.Message';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.mathgame.protobuf.Message.oneofGroups_ = [[2,3]];

/**
 * @enum {number}
 */
proto.mathgame.protobuf.Message.PayloadCase = {
  PAYLOAD_NOT_SET: 0,
  JOIN: 2,
  ANSWER: 3
};

/**
 * @return {proto.mathgame.protobuf.Message.PayloadCase}
 */
proto.mathgame.protobuf.Message.prototype.getPayloadCase = function() {
  return /** @type {proto.mathgame.protobuf.Message.PayloadCase} */(jspb.Message.computeOneofCase(this, proto.mathgame.protobuf.Message.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mathgame.protobuf.Message.prototype.toObject = function(opt_includeInstance) {
  return proto.mathgame.protobuf.Message.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mathgame.protobuf.Message} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mathgame.protobuf.Message.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    join: (f = msg.getJoin()) && mathgame_protobuf_client_pb.Join.toObject(includeInstance, f),
    answer: (f = msg.getAnswer()) && mathgame_protobuf_client_pb.Answer.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mathgame.protobuf.Message}
 */
proto.mathgame.protobuf.Message.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mathgame.protobuf.Message;
  return proto.mathgame.protobuf.Message.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mathgame.protobuf.Message} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mathgame.protobuf.Message}
 */
proto.mathgame.protobuf.Message.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.mathgame.protobuf.Message.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = new mathgame_protobuf_client_pb.Join;
      reader.readMessage(value,mathgame_protobuf_client_pb.Join.deserializeBinaryFromReader);
      msg.setJoin(value);
      break;
    case 3:
      var value = new mathgame_protobuf_client_pb.Answer;
      reader.readMessage(value,mathgame_protobuf_client_pb.Answer.deserializeBinaryFromReader);
      msg.setAnswer(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mathgame.protobuf.Message.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mathgame.protobuf.Message.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mathgame.protobuf.Message} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mathgame.protobuf.Message.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getJoin();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      mathgame_protobuf_client_pb.Join.serializeBinaryToWriter
    );
  }
  f = message.getAnswer();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      mathgame_protobuf_client_pb.Answer.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.mathgame.protobuf.Message.Type = {
  CLIENT_JOIN: 0,
  CLIENT_ANSWER: 1
};

/**
 * optional Type type = 1;
 * @return {!proto.mathgame.protobuf.Message.Type}
 */
proto.mathgame.protobuf.Message.prototype.getType = function() {
  return /** @type {!proto.mathgame.protobuf.Message.Type} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.mathgame.protobuf.Message.Type} value
 * @return {!proto.mathgame.protobuf.Message} returns this
 */
proto.mathgame.protobuf.Message.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional Join join = 2;
 * @return {?proto.mathgame.protobuf.Join}
 */
proto.mathgame.protobuf.Message.prototype.getJoin = function() {
  return /** @type{?proto.mathgame.protobuf.Join} */ (
    jspb.Message.getWrapperField(this, mathgame_protobuf_client_pb.Join, 2));
};


/**
 * @param {?proto.mathgame.protobuf.Join|undefined} value
 * @return {!proto.mathgame.protobuf.Message} returns this
*/
proto.mathgame.protobuf.Message.prototype.setJoin = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.mathgame.protobuf.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mathgame.protobuf.Message} returns this
 */
proto.mathgame.protobuf.Message.prototype.clearJoin = function() {
  return this.setJoin(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mathgame.protobuf.Message.prototype.hasJoin = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Answer answer = 3;
 * @return {?proto.mathgame.protobuf.Answer}
 */
proto.mathgame.protobuf.Message.prototype.getAnswer = function() {
  return /** @type{?proto.mathgame.protobuf.Answer} */ (
    jspb.Message.getWrapperField(this, mathgame_protobuf_client_pb.Answer, 3));
};


/**
 * @param {?proto.mathgame.protobuf.Answer|undefined} value
 * @return {!proto.mathgame.protobuf.Message} returns this
*/
proto.mathgame.protobuf.Message.prototype.setAnswer = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.mathgame.protobuf.Message.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mathgame.protobuf.Message} returns this
 */
proto.mathgame.protobuf.Message.prototype.clearAnswer = function() {
  return this.setAnswer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mathgame.protobuf.Message.prototype.hasAnswer = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto.mathgame.protobuf);
