/* eslint-disable */
// source: mathgame/protobuf/client.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.mathgame.protobuf.Answer', null, global);
goog.exportSymbol('proto.mathgame.protobuf.Command', null, global);
goog.exportSymbol('proto.mathgame.protobuf.Command.PayloadCase', null, global);
goog.exportSymbol('proto.mathgame.protobuf.Command.Type', null, global);
goog.exportSymbol('proto.mathgame.protobuf.StartGame', null, global);
goog.exportSymbol('proto.mathgame.protobuf.StartGame.Type', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mathgame.protobuf.Command = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.mathgame.protobuf.Command.oneofGroups_);
};
goog.inherits(proto.mathgame.protobuf.Command, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mathgame.protobuf.Command.displayName = 'proto.mathgame.protobuf.Command';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mathgame.protobuf.StartGame = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mathgame.protobuf.StartGame, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mathgame.protobuf.StartGame.displayName = 'proto.mathgame.protobuf.StartGame';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mathgame.protobuf.Answer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mathgame.protobuf.Answer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mathgame.protobuf.Answer.displayName = 'proto.mathgame.protobuf.Answer';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.mathgame.protobuf.Command.oneofGroups_ = [[10,11]];

/**
 * @enum {number}
 */
proto.mathgame.protobuf.Command.PayloadCase = {
  PAYLOAD_NOT_SET: 0,
  START_GAME: 10,
  ANSWER: 11
};

/**
 * @return {proto.mathgame.protobuf.Command.PayloadCase}
 */
proto.mathgame.protobuf.Command.prototype.getPayloadCase = function() {
  return /** @type {proto.mathgame.protobuf.Command.PayloadCase} */(jspb.Message.computeOneofCase(this, proto.mathgame.protobuf.Command.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mathgame.protobuf.Command.prototype.toObject = function(opt_includeInstance) {
  return proto.mathgame.protobuf.Command.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mathgame.protobuf.Command} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mathgame.protobuf.Command.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    playerId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    startGame: (f = msg.getStartGame()) && proto.mathgame.protobuf.StartGame.toObject(includeInstance, f),
    answer: (f = msg.getAnswer()) && proto.mathgame.protobuf.Answer.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mathgame.protobuf.Command}
 */
proto.mathgame.protobuf.Command.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mathgame.protobuf.Command;
  return proto.mathgame.protobuf.Command.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mathgame.protobuf.Command} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mathgame.protobuf.Command}
 */
proto.mathgame.protobuf.Command.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.mathgame.protobuf.Command.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlayerId(value);
      break;
    case 10:
      var value = new proto.mathgame.protobuf.StartGame;
      reader.readMessage(value,proto.mathgame.protobuf.StartGame.deserializeBinaryFromReader);
      msg.setStartGame(value);
      break;
    case 11:
      var value = new proto.mathgame.protobuf.Answer;
      reader.readMessage(value,proto.mathgame.protobuf.Answer.deserializeBinaryFromReader);
      msg.setAnswer(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mathgame.protobuf.Command.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mathgame.protobuf.Command.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mathgame.protobuf.Command} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mathgame.protobuf.Command.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getPlayerId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStartGame();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.mathgame.protobuf.StartGame.serializeBinaryToWriter
    );
  }
  f = message.getAnswer();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.mathgame.protobuf.Answer.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.mathgame.protobuf.Command.Type = {
  JOIN_ROOM: 0,
  START_GAME: 1,
  ANSWER: 2
};

/**
 * optional Type type = 1;
 * @return {!proto.mathgame.protobuf.Command.Type}
 */
proto.mathgame.protobuf.Command.prototype.getType = function() {
  return /** @type {!proto.mathgame.protobuf.Command.Type} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.mathgame.protobuf.Command.Type} value
 * @return {!proto.mathgame.protobuf.Command} returns this
 */
proto.mathgame.protobuf.Command.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string player_id = 2;
 * @return {string}
 */
proto.mathgame.protobuf.Command.prototype.getPlayerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.mathgame.protobuf.Command} returns this
 */
proto.mathgame.protobuf.Command.prototype.setPlayerId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional StartGame start_game = 10;
 * @return {?proto.mathgame.protobuf.StartGame}
 */
proto.mathgame.protobuf.Command.prototype.getStartGame = function() {
  return /** @type{?proto.mathgame.protobuf.StartGame} */ (
    jspb.Message.getWrapperField(this, proto.mathgame.protobuf.StartGame, 10));
};


/**
 * @param {?proto.mathgame.protobuf.StartGame|undefined} value
 * @return {!proto.mathgame.protobuf.Command} returns this
*/
proto.mathgame.protobuf.Command.prototype.setStartGame = function(value) {
  return jspb.Message.setOneofWrapperField(this, 10, proto.mathgame.protobuf.Command.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mathgame.protobuf.Command} returns this
 */
proto.mathgame.protobuf.Command.prototype.clearStartGame = function() {
  return this.setStartGame(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mathgame.protobuf.Command.prototype.hasStartGame = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional Answer answer = 11;
 * @return {?proto.mathgame.protobuf.Answer}
 */
proto.mathgame.protobuf.Command.prototype.getAnswer = function() {
  return /** @type{?proto.mathgame.protobuf.Answer} */ (
    jspb.Message.getWrapperField(this, proto.mathgame.protobuf.Answer, 11));
};


/**
 * @param {?proto.mathgame.protobuf.Answer|undefined} value
 * @return {!proto.mathgame.protobuf.Command} returns this
*/
proto.mathgame.protobuf.Command.prototype.setAnswer = function(value) {
  return jspb.Message.setOneofWrapperField(this, 11, proto.mathgame.protobuf.Command.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mathgame.protobuf.Command} returns this
 */
proto.mathgame.protobuf.Command.prototype.clearAnswer = function() {
  return this.setAnswer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mathgame.protobuf.Command.prototype.hasAnswer = function() {
  return jspb.Message.getField(this, 11) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mathgame.protobuf.StartGame.prototype.toObject = function(opt_includeInstance) {
  return proto.mathgame.protobuf.StartGame.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mathgame.protobuf.StartGame} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mathgame.protobuf.StartGame.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    numProblems: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mathgame.protobuf.StartGame}
 */
proto.mathgame.protobuf.StartGame.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mathgame.protobuf.StartGame;
  return proto.mathgame.protobuf.StartGame.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mathgame.protobuf.StartGame} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mathgame.protobuf.StartGame}
 */
proto.mathgame.protobuf.StartGame.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.mathgame.protobuf.StartGame.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNumProblems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mathgame.protobuf.StartGame.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mathgame.protobuf.StartGame.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mathgame.protobuf.StartGame} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mathgame.protobuf.StartGame.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getNumProblems();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.mathgame.protobuf.StartGame.Type = {
  ADDITION: 0,
  SUBTRACTION: 1,
  MULTIPLICATION: 2
};

/**
 * optional Type type = 1;
 * @return {!proto.mathgame.protobuf.StartGame.Type}
 */
proto.mathgame.protobuf.StartGame.prototype.getType = function() {
  return /** @type {!proto.mathgame.protobuf.StartGame.Type} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.mathgame.protobuf.StartGame.Type} value
 * @return {!proto.mathgame.protobuf.StartGame} returns this
 */
proto.mathgame.protobuf.StartGame.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional int32 num_problems = 2;
 * @return {number}
 */
proto.mathgame.protobuf.StartGame.prototype.getNumProblems = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.mathgame.protobuf.StartGame} returns this
 */
proto.mathgame.protobuf.StartGame.prototype.setNumProblems = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mathgame.protobuf.Answer.prototype.toObject = function(opt_includeInstance) {
  return proto.mathgame.protobuf.Answer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mathgame.protobuf.Answer} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mathgame.protobuf.Answer.toObject = function(includeInstance, msg) {
  var f, obj = {
    answer: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mathgame.protobuf.Answer}
 */
proto.mathgame.protobuf.Answer.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mathgame.protobuf.Answer;
  return proto.mathgame.protobuf.Answer.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mathgame.protobuf.Answer} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mathgame.protobuf.Answer}
 */
proto.mathgame.protobuf.Answer.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAnswer(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mathgame.protobuf.Answer.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mathgame.protobuf.Answer.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mathgame.protobuf.Answer} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mathgame.protobuf.Answer.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAnswer();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 answer = 1;
 * @return {number}
 */
proto.mathgame.protobuf.Answer.prototype.getAnswer = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.mathgame.protobuf.Answer} returns this
 */
proto.mathgame.protobuf.Answer.prototype.setAnswer = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


goog.object.extend(exports, proto.mathgame.protobuf);
