# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mathgame/protobuf/app.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mathgame.protobuf import client_pb2 as mathgame_dot_protobuf_dot_client__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mathgame/protobuf/app.proto',
  package='mathgame.protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1bmathgame/protobuf/app.proto\x12\x11mathgame.protobuf\x1a\x1emathgame/protobuf/client.proto\"\xc5\x01\n\x07Message\x12-\n\x04type\x18\x01 \x01(\x0e\x32\x1f.mathgame.protobuf.Message.Type\x12\'\n\x04join\x18\x02 \x01(\x0b\x32\x17.mathgame.protobuf.JoinH\x00\x12+\n\x06\x61nswer\x18\x03 \x01(\x0b\x32\x19.mathgame.protobuf.AnswerH\x00\"*\n\x04Type\x12\x0f\n\x0b\x43LIENT_JOIN\x10\x00\x12\x11\n\rCLIENT_ANSWER\x10\x01\x42\t\n\x07payloadb\x06proto3'
  ,
  dependencies=[mathgame_dot_protobuf_dot_client__pb2.DESCRIPTOR,])



_MESSAGE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='mathgame.protobuf.Message.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CLIENT_JOIN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLIENT_ANSWER', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=227,
  serialized_end=269,
)
_sym_db.RegisterEnumDescriptor(_MESSAGE_TYPE)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='mathgame.protobuf.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='mathgame.protobuf.Message.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='join', full_name='mathgame.protobuf.Message.join', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='answer', full_name='mathgame.protobuf.Message.answer', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MESSAGE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='mathgame.protobuf.Message.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=83,
  serialized_end=280,
)

_MESSAGE.fields_by_name['type'].enum_type = _MESSAGE_TYPE
_MESSAGE.fields_by_name['join'].message_type = mathgame_dot_protobuf_dot_client__pb2._JOIN
_MESSAGE.fields_by_name['answer'].message_type = mathgame_dot_protobuf_dot_client__pb2._ANSWER
_MESSAGE_TYPE.containing_type = _MESSAGE
_MESSAGE.oneofs_by_name['payload'].fields.append(
  _MESSAGE.fields_by_name['join'])
_MESSAGE.fields_by_name['join'].containing_oneof = _MESSAGE.oneofs_by_name['payload']
_MESSAGE.oneofs_by_name['payload'].fields.append(
  _MESSAGE.fields_by_name['answer'])
_MESSAGE.fields_by_name['answer'].containing_oneof = _MESSAGE.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'mathgame.protobuf.app_pb2'
  # @@protoc_insertion_point(class_scope:mathgame.protobuf.Message)
  })
_sym_db.RegisterMessage(Message)


# @@protoc_insertion_point(module_scope)
